import Head from 'next/head'
import Link from "next/link"
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div  className=' p5-2 pr-5 pl-5 pt-5 bg-[#F9FBFB] w-screen h-screen'>
      <Head>
        <title>asteve erc20 token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <section  className=' '>
        <div className='w-full h-auto  flex justify-between flex-row'>
          <h2 className=' text-[30px] font-bold text-[#009393]'>AST TOKEN</h2>
          <Link  href="/dashboard">
            <button className='p-5 h-[50px] box-border rounded-xl bg-[#009393]  text-[#F9FBFB] flex items-center justify-center'>
            Dashboard</button></Link>

        </div>
        <div className='text-center mt-40 font-bold text-[20px]'>
          These is a Interface representing my implementation of ERC20 token 
          <button className='ml-auto mr-auto mt-5 p-5 h-[50px] box-border rounded-xl bg-[#009393]  text-[#F9FBFB] flex items-center justify-center'>
            Dashboard</button>
          </div>
        
      </section>
      
     
    </div>
  )
}
